apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
        - name: basket-api
          image: cmdev1997/basket-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secret-basket
                  key: ConnectionStrings__DefaultConnection