apiVersion: v1
kind: Service
metadata:
  name: basket-api
  labels:
    app: basket-api
spec:
  type: ClusterIP
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
