apiVersion: v1
kind: Service
metadata:
  name: discount-grpc
  labels:
    app: discount-grpc
spec:
  type: ClusterIP
  selector:
    app: discount-grpc
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: grpc
      protocol: TCP
      port: 9002
      targetPort: 9002
