env:
  ENVIRONMENT: dev
  SOME_FLAG: "true"

configmap:
  GrpcSettings__DiscountUrl: "http://discount-grpc:9002"

secrets:
  db:
    ConnectionStrings__DefaultConnection: "Server=103.221.223.177;Port=30010;Database=basket;User Id=admin;Password=admin@123;Include Error Detail=true"

image:
  repository: cmdev1997/basket-api
  tag: dev-latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: http-dev
      port: 80
      targetPort: 80
    - name: grpc-dev
      port: 5001
      targetPort: 5001

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
