name: CI - Basket.API

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Detect environment & set tag
        id: setenv
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "TAG=dev-latest" >> $GITHUB_ENV
            echo "NAME=CI - Basket.API [dev]" >> $GITHUB_ENV
          elif [ "$BRANCH" = "staging" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "TAG=staging-latest" >> $GITHUB_ENV
            echo "NAME=CI - Basket.API [staging]" >> $GITHUB_ENV
          elif [ "$BRANCH" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
            echo "TAG=prod-latest" >> $GITHUB_ENV
            echo "NAME=CI - Basket.API [prod]" >> $GITHUB_ENV
          else
            echo "❌ Branch không hợp lệ cho CI"
            exit 1
          fi

      - name: Set dynamic workflow name
        run: echo "${{ env.NAME }}"

      - name: Build & Push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Services/Basket/Basket.API/Dockerfile
          push: true
          tags: cmdev1997/basket-api:${{ env.TAG }}
