name: CI - Basket.API

on:
  push:
    paths:
      - 'src/Services/Basket/**'
  pull_request:
    paths:
      - 'src/Services/Basket/**'

jobs:
  build-and-test:
    name: Build & Test Basket.API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # sửa lại nếu dùng .NET khác

      - name: Restore
        run: dotnet restore src/Services/Basket/Basket.API/Basket.API.csproj

      - name: Build
        run: dotnet build src/Services/Basket/Basket.API/Basket.API.csproj --no-restore --configuration Release

      - name: Test
        run: |
          echo "✅ No test project found yet for Basket.API. Add a test project to enable test step."
          # dotnet test path/to/test-project.csproj --no-build --configuration Release
