name: CD - Deploy Basket.API to K3s

on:
  workflow_run:
    workflows:
      - "CI - Basket.API [dev]"
      - "CI - Basket.API [staging]"
      - "CI - Basket.API [prod]"
    types:
      - completed

jobs:
  deploy:
    name: Deploy to K3s with Helm
    runs-on: ubuntu-latest

    steps:
      - name: Lấy branch vừa chạy CI
        run: echo "BRANCH_NAME=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Xác định ENVIRONMENT theo branch
        id: envmap
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [ "${{ github.event.workflow_run.head_branch }}" = "staging" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [ "${{ github.event.workflow_run.head_branch }}" = "main" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "❌ Branch không hợp lệ cho CD"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Helm Deploy to K3s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            echo "🚀 Bắt đầu deploy Basket.API cho môi trường ${{ env.ENV }}"

            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            cd ~/app || git clone https://github.com/congminh2812/EShopMicroservices.git ~/app
            cd ~/app && git pull origin ${{ github.event.workflow_run.head_branch }}

            echo "📄 Deploy Helm với values-${{ env.ENV }}.yaml"
            helm upgrade --install basket-api ./infra/helm/basket \
              -f ./infra/helm/basket/values-${{ env.ENV }}.yaml \
              -n default

            echo "📊 Kiểm tra rollout"
            kubectl rollout status deployment basket-api -n default

            echo "✅ Deploy Basket.API cho môi trường ${{ env.ENV }} hoàn tất!"
