name: CD - Deploy Basket.API to K3s

on:
  workflow_run:
    workflows: ["CI - Basket.API"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to K3s with Helm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Helm Deploy to K3s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            echo "🚀 Bắt đầu deploy Basket.API bằng Helm"

            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            echo "📦 Pull source code mới nhất"
            cd ~/app || git clone https://github.com/congminh2812/EShopMicroservices.git ~/app
            cd ~/app && git pull origin main

            echo "📄 Tạo configmap và secret từ Helm values"
            helm upgrade --install basket-api ./infra/helm/basket \
              -f ./infra/helm/basket/values-dev.yaml \
              -n default

            echo "📊 Kiểm tra rollout"
            kubectl rollout status deployment basket-api -n default

            echo "✅ Deploy Basket.API hoàn tất!"
