name: Deploy Kong Gateway (DB mode)

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/deploy-kong.yaml'

jobs:
  deploy-kong:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Decode kubeconfig
        run: |
          echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig.yaml
          echo "KUBECONFIG=$PWD/kubeconfig.yaml" >> $GITHUB_ENV
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Kong Helm repo
        run: |
          helm repo add kong https://charts.konghq.com
          helm repo update

      - name: Deploy Kong with PostgreSQL (DB mode)
        run: |
          export KUBECONFIG=$PWD/kubeconfig.yaml
          helm upgrade --install kong kong/kong \
            --namespace kong --create-namespace \
            --set ingressController.enabled=true \
            --set env.database=postgres \
            --set postgresql.enabled=true \
            --set env.pg_user=kong \
            --set env.pg_password=kong \
            --set env.pg_database=kong \
            --set env.pg_host=kong-postgresql.kong.svc.cluster.local \
            --wait

      - name: Wait for Kong to be ready
        run: |
          echo "⏳ Waiting for Kong to be ready..."
          sleep 30

      - name: Setup Kong services & routes (basket)
        run: |
          chmod +x ./scripts/kong-basket-setup.sh
          ./scripts/kong-basket-setup.sh ${{ secrets.KONG_ADMIN_URL }}
