name: CI - Discount.Grpc

on:
  push:
    paths:
      - 'src/Services/Discount/**'
  pull_request:
    paths:
      - 'src/Services/Discount/**'

jobs:
  build-and-test:
    name: Build & Test Discount.Grpc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # sửa lại nếu dùng .NET khác

      - name: Restore
        run: dotnet restore src/Services/Discount/Discount.Grpc/Discount.Grpc.csproj

      - name: Build
        run: dotnet build src/Services/Discount/Discount.Grpc/Discount.Grpc.csproj --no-restore --configuration Release

      - name: Test
        run: |
          echo "✅ No test project found yet for Discount.Grpc. Add a test project to enable test step."
          # dotnet test path/to/test-project.csproj --no-build --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Services/Discount/Discount.Grpc/Dockerfile
          push: true
          tags: cmdev1997/discount-grpc:latest